In [20]:
import os
import sys
import random
import warnings
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use('agg')
import matplotlib.pyplot as plt
from tqdm import tqdm
from itertools import chain
from skimage.io import imread, imshow, imread_collection, concatenate_images
from skimage.transform import resize
import json
from skimage import draw
from skimage import io
from skimage.draw import ellipse
import cv2
import tifffile
from IPython.display import Image
import matplotlib.image as mpimg
matplotlib.use('TkAgg')
from operator import itemgetter
from PIL import Image
import bz2
import glob
import argparse

In [69]:
path_image="data/training/"
path_json="data/trainjson/"
output_folder="data/output/"
paths="data/images/*.*"

In [70]:
def image_binary(path):
    
    for files_name in [file for file in os.listdir(path) if file.endswith('.json')]:
        f1=os.path.splitext(files_name)[0]
        print(f1)
        
        for file in glob.glob(paths):
            f2=file.split()[0][12:-4]
            if (f1==f2):
                
                with open(path + files_name) as json_file:
                    d=json.load(json_file)
                    img = cv2.imread(file)
                    k = cv2.waitKey(0)
                    cv2.destroyAllWindows()
                    img=img.copy()
                    x=list(map(itemgetter('points'),d['shapes']))
                    polygon_numpy=np.array(x)
                    p = polygon_numpy.squeeze()
                    r, c = draw.polygon(p[:,1],p[:,0])
                    img[r,c]=0
                    grayImage = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
                    (thresh,blackAndWhiteImage) = cv2.threshold(grayImage,1, 255, cv2.THRESH_BINARY)
                    data=Image.fromarray(blackAndWhiteImage)
                    save_fname = os.path.join(output_folder, os.path.basename(f1)+'.jpg')
                    data.save(save_fname) 
                
            else:
                print('a')
           
            

In [71]:
image_binary(path_image)

1
a
a
a
a
a
a
1280px-German_Shepherd_Dog_with_disc
a
a
a
a
a
a
14-german-shepherd-CruftsChannel4
a
a
a
a
a
a
3451e49fa7e5f3584138c4cbb983112e
a
a
a
a
a
a
Correct-Type-Best-in-Show-Westminster-2017-RUMOR
a
a
a
a
a
a
Dog_Golden-Retriever_Mobile
a
a
a
a
a
a
German_Shepherd_-_DSC_0346_(10096362833)
a
a
a
a
a
a


In [54]:
for file in glob.glob(path):
    
    print(file)
    print(file.split()[0][12:-4])
    a= cv2.imread(file)
    print(a)
    #c = cv2.cvtColor(a, cv2.COLOR_BGR2RGB)
    #cv2.imshow('Color image', c)
    #wait for 1 second
    k = cv2.waitKey(1000)
    #destroy the window
    cv2.destroyAllWindows()

data/images\1.jpg
1
[[[157 158 162]
  [156 157 161]
  [155 156 160]
  ...
  [137 161 167]
  [143 167 173]
  [146 170 176]]

 [[154 155 159]
  [154 155 159]
  [153 155 156]
  ...
  [136 161 165]
  [143 168 172]
  [146 171 175]]

 [[149 153 154]
  [149 153 154]
  [148 153 152]
  ...
  [136 161 165]
  [142 167 171]
  [145 170 174]]

 ...

 [[155 190 170]
  [151 187 171]
  [143 180 170]
  ...
  [ 57 103  80]
  [ 47  93  70]
  [ 39  85  62]]

 [[129 164 137]
  [106 145 119]
  [105 154 126]
  ...
  [ 26  63  59]
  [ 46  83  79]
  [ 62  99  95]]

 [[149 185 149]
  [102 145 108]
  [113 168 129]
  ...
  [ 48 104  85]
  [ 75 131 112]
  [ 67 123 104]]]
data/images\1280px-German_Shepherd_Dog_with_disc.jpg
1280px-German_Shepherd_Dog_with_disc
[[[100 179 138]
  [ 98 177 136]
  [ 95 174 135]
  ...
  [ 82 184 137]
  [ 73 175 128]
  [ 81 183 136]]

 [[105 184 143]
  [100 179 138]
  [ 92 171 132]
  ...
  [ 73 175 128]
  [ 65 167 120]
  [ 68 170 123]]

 [[106 185 144]
  [100 179 138]
  [ 92 171 130]
  ..

In [ ]:
x=os.listdir("data/trainjson/")

In [69]:
for file_name in [file for file in os.listdir(path_image) if file.endswith('.jpg')]:
        print(file_name)

1.jpg
1280px-German_Shepherd_Dog_with_disc.jpg
14-german-shepherd-CruftsChannel4.jpg
3451e49fa7e5f3584138c4cbb983112e.jpg
Correct-Type-Best-in-Show-Westminster-2017-RUMOR.jpg


In [34]:
for file_name in [file for file in os.listdir(path_json) if file.endswith('.json')]:
    with open(path_json + file_name) as json_file:
        d = json.load(json_file)
        x=list(map(itemgetter('points'),d['shapes']))

In [ ]:
from operator import itemgetter
x=list(map(itemgetter('points'),d['shapes']))

In [ ]:
from PIL import Image

In [ ]:
h = d['imageHeight']
w = d['imageWidth']

In [20]:
img = plt.imread("1.jpg")

In [27]:
print(type(img))

<class 'numpy.ndarray'>


In [ ]:
img=img.copy()

In [13]:
i=cv2.imread('data/images/1280px-German_Shepherd_Dog_with_disc.jpg')

In [14]:
print(type(i))

<class 'numpy.ndarray'>


In [19]:
i.co

(480, 852, 3)

In [ ]:
polygon_numpy=np.array(x)

In [ ]:
polygon_numpy.shape

In [ ]:
p = polygon_numpy.squeeze()
p.shape

In [ ]:
r, c = draw.polygon(p[:,1],p[:,0])

In [ ]:
img[r,c]=0

In [ ]:
plt.imshow(img)
plt.show()

In [ ]:
data=Image.fromarray(img)
data.save('gfg_dummy_pic1.png') 

In [ ]:
grayImage = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

In [ ]:
plt.imshow(grayImage)
plt.show()

In [ ]:
(thresh, blackAndWhiteImage) = cv2.threshold(grayImage,1, 255, cv2.THRESH_BINARY)

In [ ]:
plt.imshow(blackAndWhiteImage)
plt.show()

In [ ]:
len(r)

In [ ]:
blackAndWhiteImage